### ISSUE TITLE
ValueError: not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by fayazdharejo** [hieubkset/Keras-Image-Super-Resolution#1]
I am receiving this error during running models, could you please guide me ? is my command is correct ?

(tensorflow1) D:\Keras-Image-Super-Resolution-master\Keras-Image-Super-Resolution-master>python pretrain.py --arc=edsr --train=/data/DIV2K_train_HR/DIV2K_train_HR --train-ext=.png --valid=data/DIV2K_valid_HR/DIV2K_valid_HR --valid-ext=.png --init_epoch=10 --cuda=1

** Loading training images
Traceback (most recent call last):
  File "pretrain.py", line 147, in <module>
    main()
  File "pretrain.py", line 143, in main
    train(**params)
  File "pretrain.py", line 70, in train
    lr_hr_ds, n_data = data.load_train_dataset(params['lr_dir'], params['hr_dir'], params['ext'], params['batch_size'])
  File "D:\Keras-Image-Super-Resolution-master\Keras-Image-Super-Resolution-master\data.py", line 53, in load_train_dataset
    lr_hr_ds, n_data = get_dataset(lr_path, hr_path, ext)
  File "D:\Keras-Image-Super-Resolution-master\Keras-Image-Super-Resolution-master\data.py", line 41, in get_dataset
    lr_sorted_paths, hr_sorted_paths = zip(*lr_hr_sorted_paths)
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by hieubkset** [comment]
I think you downloaded DIV2K dataset, and extract it to data folder. Afterwards, you run the code but it did not work. 

Actually, DIV2K dataset only contains high resolution images (HR image) and does not contains low resolution images (LR images).
So to run the code, you have to generate LR images first. You can do it by using matlab scripts (https://github.com/hieubkset/Keras-Image-Super-Resolution/tree/master/data_preprocess).
For training LR images, there are two scripts:
- aug_data_div2k.m: generate LR images by using bicubic interpolation with scale 4.
- aug_data_div2k_half.m: generate LR images by using bicubic interpolation with scale 2.
For testing LR images, using the script testset_bicubic_downsample.m
These scripts will search all HR images from a HR folder, and then generate LR images to a LR folder.
So you need to modify first lines of these scripts to your HR and LR folder.

Please note that
 --train and --valid arguments should point to a folder that contains a LR folder and a HR folder.
For example,
--train=data/train/DIV2K so you should have 'data/train/DIV2K/HR' and 'data/train/DIV2K/LR'. 
--valid=data/test/Set5 so you should have 'data/test/Set5/HR' and 'data/test/Set5/LR'

**Comment by fayazdharejo** [comment]
> 
> 
> I think you downloaded DIV2K dataset, and extract it to data folder. Afterwards, you run the code but it did not work.
> 
> Actually, DIV2K dataset only contains high resolution images (HR image) and does not contains low resolution images (LR images).
> So to run the code, you have to generate LR images first. You can do it by using matlab scripts (https://github.com/hieubkset/Keras-Image-Super-Resolution/tree/master/data_preprocess).
> For training LR images, there are two scripts:
> 
>     * aug_data_div2k.m: generate LR images by using bicubic interpolation with scale 4.
> 
>     * aug_data_div2k_half.m: generate LR images by using bicubic interpolation with scale 2.
> 
> 
> For testing LR images, using the script testset_bicubic_downsample.m
> These scripts will search all HR images from a HR folder, and then generate LR images to a LR folder.
> So you need to modify first lines of these scripts to your HR and LR folder.
> 
> I'm sorry because it takes a little bit of time for completing this step.
> 
> Please note that
> --train and --valid arguments should point to a folder that contains a LR folder and a HR folder.
> For example,
> --train=data/train/DIV2K so you should have 'data/train/DIV2K/HR' and 'data/train/DIV2K/LR'.
> --valid=data/test/Set5 so you should have 'data/test/Set5/HR' and 'data/test/Set5/LR'

Thank you very much for your guidance, and time. i am confused at dataset preparation step. as you said "DIV2K dataset  which consists of 800 HR training images and 100 HR validation images."  we have to apply data augmentation step on **DIV2K_train_HR images**??  or on on both folder **DIV2K_train_HR images** and **DIV2K_valid_HR images**??                                                                    **Another confusion is:** i did augmentation on both **DIV2K_train_HR**  and **DIV2K_valid_HR** folders.      and code generates **GT** and **LR_bicubic**  for each folders.  then on which folder i have to apply **trainning step**? either GT or **LR_bicubic**

**Comment by hieubkset** [comment]
Answer your first question:
I applied data augmentation on both folders of DIV2K dataset, and  used Set5 dataset for validation. You can download Set5 from http://vllab.ucmerced.edu/wlai24/LapSRN/results/SR_testing_datasets.zip.
However, if you want to use validation set for early stopping or selecting the best model, you should not use Set5 for validation. The reason is that Set5 (and Set14, BSDS100) are often used for reporting testing results (PSNR & SSIM). 

Answer your second question:
You should  put GT and LR_bicubic folder into a folder (data/train/DIV2K).
For example,
--train=data/train/DIV2K
and then 'data/train/DIV2K' folder have 2 sub folders: 'data/train/DIV2K/GT' and 'data/train/DIV2K/LR_bicubic'

**Comment by fayazdharejo** [comment]
![DIV2k](https://user-images.githubusercontent.com/44371159/61926512-6d4fff00-afa3-11e9-8d39-5d54e063f519.JPG)

**Comment by fayazdharejo** [comment]
according to above image, is it right sir? should i put all images GT, LR_bicubic  generated from DIV2K_train_HR and DIV2K_valid_HR in to one  DIV2k folder?

**Comment by hieubkset** [comment]
It's right!
