### ISSUE TITLE
About RCAN Network

### ISSUE THREAD

**Issue by RyotaImai** [hieubkset/Keras-Image-Super-Resolution#12]
Hi. Let me ask you an elementary question.
Is the code below correct?
https://github.com/hieubkset/Keras-Image-Super-Resolution/blob/2bbde6e8488a65bb40458eb164c091811328c368/model/rcan.py#L33

I think this part is 
```
x = ca(x, filters) 
```
I'm sorry if this is a misguided question.

**Comment by hieubkset** [comment]
Thank you! It was fixed.
