### ISSUE TITLE
og_folder

### ISSUE THREAD

**Issue by fayazdharejo** [hieubkset/Keras-Image-Super-Resolution#2]
can you please tell me what is **og_folder** in **testset_bicubic_doensample.m** file ?

**Comment by hieubkset** [comment]
There is some images from Set14, BSDS100 whose width and height are not divisible by 4, so they should be cropped. I saved original images into og_folder, cropping images into hr_folder, and bicubic downsampling images into lr_folder.

**Comment by hieubkset** [comment]
After extracting testing dataset, assume that there are 14 images in 'data/test/Set14' folder. Then do the following scripts
```
cd data/test/Set14
mkdir OG
mv *.png OG/
mkdir HR
mkdir LR
```
Modifying testset_bicubic_downsample.m
```
folder = 'data/test/Set14/';
og_folder = strcat(folder, 'OG/');
hr_folder = strcat(folder, 'HR/');
lr_folder = strcat(folder, 'LR/');
```
then you can run the matlab script.
