### ISSUE TITLE
Is Relativistic discriminator implemented for ESRGAN?

### ISSUE THREAD

**Issue by kaaviyave** [hieubkset/Keras-Image-Super-Resolution#7]
Hi @hieubkset , Thank you for this wonderful repo. 

If I follow correctly, you are using a standard discriminator for ESRGAN as well. Or if the rad/relativistic discriminator loss is being used, could you point me to this part of the code please?

**Comment by hieubkset** [comment]
You are right! It's a standard discriminator.
